### PR TITLE
Bump version 0.11.5

### PR DESCRIPTION
**Pull request by cmutel**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cmutel** [comment]
@conda-forge-admin, please rerender

**Review by m-rossi — APPROVED** [review]

**Comment by m-rossi** [comment]
@cmutel it is not necessary, that you manually create the PRs for new versions. The _bot_ should create PRs once it detects new versions

**Comment by cmutel** [comment]
@m-rossi I know, but sometimes you need it done for a class starting in 15 minutes instead of waiting maybe an hour or two :p

**Comment by m-rossi** [comment]
Ok valid edgecase. Hope the packages are available fast enough.

**Pull request merged**
